### ISSUE TITLE
Ubuntu 22.04 & MongoDB Install

### ISSUE THREAD

**Issue by Tukachinchilla** [p0ntsNL/hodlv2#34]
Ubuntu 22.04 does not have a mongoDB install so it will fail.  If you still want to install you need to manually install the dependencies:

1.  Download the package depending on what you are installing on:

- amd64

`wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
`
- arm64 (use this for Raspberry Pi)

`wget http://ports.ubuntu.com/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_arm64.deb
`
- i386

`wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_i386.deb
`

2.  install the package (the below example uses arm64 for a Raspberry Pi

`sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_arm64.deb
`

3. Install MongoDB

`sudo apt-get install -y mongodb-org
`

**Comment by Tukachinchilla** [comment]
Okay, so I tried the above and it failed.  but I followed the following and got it working: https://stackoverflow.com/questions/68937131/illegal-instruction-core-dumped-mongodb-ubuntu-20-04-lts

note: you still have to start the service after doing the above steps:

`sudo service mongod  start`

and verify with 

`sudo service mongod status`

**Comment by p0ntsNL** [comment]
Following the official documentation on the MongoDB website is the recommended way.

https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/

This installation automatically takes the architecture you run on into account.
